language: node_js
node_js: "8"
cache:
  directories:
    - "node_modules"
script:
  - npm test
services:
  - mysql
before_install:
  - cp config/config-sample.js config/config.js
  - mysql -e "CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;"
  - mysql -u $DATABASE_USERNAME $DATABASE_NAME < test/travis.sql